### ISSUE TITLE
subtract_median throws MemoryError

### ISSUE THREAD

**Issue by rfinn** [rfinn/HalphaImaging#31]
# Problem

* subtract_median.py throws a MemoryError.  I'm not sure why.  Oddly, it will process a bunch and then throw the error, so for now, I just restart the process.  I tried explicitly closing each hdu after I do the med subtraction, but this doesn't seem to help.

* in 2020 data dir, it does about 20 images and then crashes.  Next time it died after 4 images. then 2 images.
* NOTE: I did not run into this problem when running subtract_sky on my laptop on the INT data.  This has only been a problem with HDI data processed on the virgo vms.

# Error Message
```
Traceback (most recent call last):
  File "/home/rfinn/github/HalphaImaging/python3/subtract_median.py", line 78, in <module>
    #print(files)
  File "/home/rfinn/github/HalphaImaging/python3/subtract_median.py", line 54, in subtract_median
    # background subtraction
  File "/home/rfinn/github/HalphaImaging/python3/imutils.py", line 26, in subtract_median_sky
    mean,median,std = sigma_clipped_stats(masked_data,sigma=3.0,cenfunc=np.ma.mean)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/astropy/stats/sigma_clipping.py", line 749, in sigma_clipped_stats
    copy=False)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/astropy/stats/sigma_clipping.py", line 468, in __call__
    copy=copy)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/astropy/stats/sigma_clipping.py", line 302, in _sigmaclip_noaxis
    self._compute_bounds(filtered_data, axis=None)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/astropy/stats/sigma_clipping.py", line 270, in _compute_bounds
    std = self.stdfunc(data, axis=axis)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/astropy/stats/sigma_clipping.py", line 85, in _nanstd
    return bottleneck.nanstd(array, axis=axis, ddof=ddof)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/bottleneck/slow/reduce.py", line 47, in nanstd
    return np.nanstd(a, axis=axis, ddof=ddof)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/numpy/lib/nanfunctions.py", line 1628, in nanstd
    keepdims=keepdims)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/numpy/lib/nanfunctions.py", line 1476, in nanvar
    arr, mask = _replace_nan(a, 0)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/numpy/lib/nanfunctions.py", line 71, in _replace_nan
    a = np.array(a, subok=True, copy=True)
MemoryError
```

# Relevant Function
```
def subtract_median_sky(data):
    ''' subtract median sky from image data '''
    mask = make_source_mask(data,nsigma=3,npixels=5,dilate_size=10)
    masked_data = np.ma.array(data,mask=mask)
    #clipped_array = sigma_clip(masked_data,cenfunc=np.ma.mean)

    mean,median,std = sigma_clipped_stats(masked_data,sigma=3.0,cenfunc=np.ma.mean)
    data -= median
    return data,median

```

# Ideas to Test

* This might be related to an issue I saw that said astropy.stats.sigma_clip stats is really slow.  I changed the centfunc to np.ma.mean  

* I have the dilate_size set to 10 is photutils.make_source_mask.  Maybe this is too much?  Not sure if this masks 10 nearest pixels, or is a scale factor.

**Comment by rfinn** [comment]
This doesn't seem to be an issue when running on draco, so closing this.
